PACKAGE_NAME="aic8800-pcie"
PACKAGE_VERSION="2.1.1"
AUTOINSTALL="yes"

MAKE="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

BUILT_MODULE_NAME[0]="aic8800D80_fdrv"
BUILT_MODULE_LOCATION[0]="aic8800_fdrv/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/aic8800/"
